replace gardener-extension-networking-cilium by fork
metal-stack/gardener-extension-provider-metal pull request #403
Opened 2024-06-04 09:42 UTC by iljarotar

2024-06-18 18:42 UTC, robertvolkmann commented on pkg/admission/mutator/defaulter.go
> +
Why do we need this?

2024-06-18 18:42 UTC, robertvolkmann commented on pkg/admission/mutator/config.go
> +	return ciliumextensionv1alpha1.LoadBalancingMode(c.string("DEFAULTER_CILIUMLOADBALANCINGMODE", string(ciliumextensionv1alpha1.SNAT)))
I still don't understand that is the desired value for metal-stack. Any idea?

2024-06-19 10:01 UTC, robertvolkmann requested changes

2024-06-19 10:22 UTC, robertvolkmann commented
`metallb` is still by the internal helm chart `shoot-control-plane`.

2024-10-23 06:13 UTC, robertvolkmann approved these changes

2024-10-23 13:47 UTC, Gerrit91 commented
Needs rebase

2024-10-24 13:03 UTC, merged